name: informa_saude
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  mobx: ^2.0.6+1
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.4
  dio: ^4.0.6
  flutter_mobx: ^2.0.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4

  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true

  assets:
    - assets/virus.png

